### ISSUE TITLE
Kofta Alarms

### ISSUE THREAD

**Issue by SamourM** [madhead/kofta#2]
should I replace, $topic-name with each topic I have or expression?

 calc: $topic-name                      (3)

Also, can i replace sysadmin with email address?

 to: sysadmin                             (8)

Thanks alot.

**Comment by madhead** [comment]
1. Yes, you should replace `$topic-name` with actual topic names
2. Most probably, it won't work. You should add email in `sysadmin` role instead. Read more here: https://docs.netdata.cloud/health/notifications/.

**Comment by SamourM** [comment]
Thanks a lot for your patience and support, appreciated.
